### ISSUE TITLE
Daemon and CLI release workflows fail loading `@semantic-release/commit-analyzer`

### ISSUE THREAD

**Issue by brunodam** [hashgraph/solo-weaver#617]
## Problem

Both release workflows (`flow-deploy-release-daemon.yaml` and `flow-deploy-release-cli.yaml`, introduced in c5163a2 / #614) fail to load semantic-release plugins. The Daemon workflow tripped first — run [26542763251](https://github.com/hashgraph/solo-weaver/actions/runs/26542763251/job/78187847747) exited with:

```
[semantic-release] › ✘  An error occurred while running semantic-release: Error: Cannot find module '@semantic-release/commit-analyzer'
Require stack:
- /home/runner/_work/solo-weaver/solo-weaver/noop.js
```

The same install step (`npm install -g semantic-release@24.2.4 @semantic-release/exec@7.1.0 conventional-changelog-conventionalcommits@8.0.0`) worked in the previous `flow-deploy-release-artifact.yaml` on 2026-05-26 because semantic-release was invoked without `--extends`, so plugin resolution fell back to the bundled plugins inside the globally-installed `semantic-release` package.

The new workflows pass `--extends "$(pwd)/.releaserc_daemon.json"` (and `.releaserc_cli.json`). With `--extends` pointing at a path inside `cwd`, semantic-release's plugin resolver anchors at the project directory (which has no `node_modules`) and can no longer reach the bundled `@semantic-release/commit-analyzer`, `@semantic-release/release-notes-generator`, or `@semantic-release/github`. Only `@semantic-release/exec` happens to be installed explicitly, so it loads.

The CLI workflow has the same latent bug; it just hasn't been triggered with a release since the rename.

## Proposed fix

Install the three missing plugins explicitly in the `Install Semantic Release` step of both workflows:

```yaml
run: npm install -g semantic-release@24.2.4 \
  @semantic-release/exec@7.1.0 \
  @semantic-release/commit-analyzer@13.0.1 \
  @semantic-release/release-notes-generator@14.1.1 \
  @semantic-release/github@11.0.6 \
  conventional-changelog-conventionalcommits@8.0.0
```

## Acceptance

- [ ] Daemon release workflow completes plugin loading and reaches the commit-analysis stage
- [ ] CLI release workflow does the same
- [ ] Plugin versions are pinned so future installs are reproducible
